post-commit asks user before installing jars

diff --git a/post-commit b/post-commit
--- a/post-commit
+++ b/post-commit
@@ -2,14 +2,22 @@
 
 # Run the test suite.
 # It will exit with 0 if it everything compiled and tested fine.
-echo "installing jars in local repo..."
-cd annotation-bundle
-mvn install
-if [ $? -eq 0 ]; then
-  exit 0
+echo "Install new jars in local maven repo (default is no)? (y/n):"
+
+read install
+
+if (("$install" == "y") || (("$install" == "Y")); then
+  echo "installing jars in local repo..."
+  cd annotation-bundle
+  mvn install
+  if [ $? -eq 0 ]; then
+    exit 0
+  else
+    echo ""
+    echo "Installing your project or running the tests failed."
+    exit 1
+  fi
 else
-  echo ""
-  echo "Installing your project or running the tests failed."
-  exit 1
+  echo "Skipped jar update."
 fi
 
